REVOKE ALL PRIVILEGES, GRANT OPTION FROM 'acore'@'%';

DROP USER 'acore'@'%';

DROP DATABASE IF EXISTS `acore_world`;

DROP DATABASE IF EXISTS `acore_characters`;

DROP DATABASE IF EXISTS `acore_auth`;
